name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome and thanks for opening your first issue!**

            A maintainer will review this issue shortly. If you'd like to work on this issue, please leave a comment and tag the `@mautic/education-team-leaders`.
          pr-message: |
            🎉 **Congratulations on opening your first PR!** 🎉

            Thank you for taking the time to improve Mautic. We truly appreciate it. ✨ 

            Come join [our Slack](https://mautic.org/slack/) if you haven't, and welcome to the Mautic Community!
